# Generated by Django 5.0.2 on 2026-04-09 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userschema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linked_student',
            field=models.ForeignKey(blank=True, help_text='If role is Parent, optionally link this account to a student profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
